name: 'datapalooza'
version: '1.0.0'
config-version: 2

profile: 'datapalooza'

source-paths: ["models"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
    - "target"
    - "dbt_modules"

models:
    datapalooza:
        materialized: table
